<?php
define("_MD_TCW_PAGE", "My Page");
define("_MD_TCW_PAGE_ADD", "Add Page");
define("_MD_TCW_PAGE_SHORT", "Page");
define("_MD_TCW_PAGEID", "Page ID");
define("_MD_TCW_PAGETITLE", "Page Title");
define("_MD_TCW_PAGECONTENT", "Page Content");
define("_MD_TCW_PAGEDATE", "Post Date");
define("_MD_TCW_PAGEUID", "Author");
define("_MD_TCW_PAGECOUNT", "Counter");
define("_MD_TCW_PAGESORT", "Sort");
define("_MD_TCW_PAGE_UPLOAD", "Upload");
define("_MD_TCW_PAGE_BLOCK_LIST", "Page List");
define("_MD_TCW_PAGE_BLOCK_MENU", "Page Menu");
define("_MD_TCW_PAGE_BLOCK_SHOW_COUNT", "Do you wnat to display counter?");
define("_MD_TCW_PAGECSS", "Content Style");
define("_MD_TCW_PAGECSS_DESC", "");
define("_MD_TCW_PAGE_LIST_PAGES_TITLE", "Show article title?");
define("_MD_TCW_PAGE_LIST_PAGES_TITLE_DESC", "If no is selected, only the category headings are displayed.");
define("_MD_TCW_PAGE_UNCATEGORY", "Uncategorized articles");
define("_MD_TCW_PAGE_SIZE1", " (");
define("_MD_TCW_PAGE_SIZE2", " articles) ");
define("_MD_TCW_PAGE_CATE", "Select the category to display");
define("_MD_TCW_PAGE_ALLCATE", "All categories");
