<?php
define('_MD_TCW_PAGE', '文章列表');
define('_MD_TCW_PAGE_ADD', '新增文章');
define('_MD_TCW_PAGE_SHORT', '文章');
define('_MD_TCW_PAGEID', '文章編號');
define('_MD_TCW_PAGETITLE', '文章標題');
define('_MD_TCW_PAGECONTENT', '文章內容');
define('_MD_TCW_PAGEDATE', '建立日期');
define('_MD_TCW_PAGEUID', '發布者');
define('_MD_TCW_PAGECOUNT', '人氣');
define('_MD_TCW_PAGESORT', '排序');
define('_MD_TCW_PAGE_UPLOAD', '上傳檔案');
define('_MD_TCW_PAGE_BLOCK_LIST', '文章列表');
define('_MD_TCW_PAGE_BLOCK_MENU', '文章選單');
define('_MD_TCW_PAGE_BLOCK_SHOW_COUNT', '是否顯示點閱數？');
define('_MD_TCW_PAGECSS', '內容外觀設定');
define('_MD_TCW_PAGECSS_DESC', 'line-height: 行距; font-size: 文字大小; background: 背景色;（此為CSS語法，不熟請維持原設定即可）');
define('_MD_TCW_PAGE_LIST_PAGES_TITLE', '列表是否顯示內文文章');
define('_MD_TCW_PAGE_LIST_PAGES_TITLE_DESC', '選否的話，就僅顯示分類大標題');
define('_MD_TCW_PAGE_UNCATEGORY', '未分類文章');
define('_MD_TCW_PAGE_SIZE1', '（共 ');
define('_MD_TCW_PAGE_SIZE2', ' 篇文章）');
define('_MD_TCW_PAGE_CATE', '選擇欲顯示分類');
define('_MD_TCW_PAGE_ALLCATE', '所有分類');
