<?php
define('_MD_TCW_NEWS', 'News');
define('_MD_TCW_NEWS_SHORT', 'Message');
define('_MD_TCW_NEWSID', 'Number');
define('_MD_TCW_NEWSTITLE', 'Message Title');
define('_MD_TCW_NEWSCONTENT', 'Message content');
define('_MD_TCW_NEWSDATE', 'Release date');
define('_MD_TCW_TOCAL', 'Save to Calendar');
define('_MD_TCW_NEWSPLACE', 'Place');
define('_MD_TCW_NEWSMASTER', 'Host');
define('_MD_TCW_NEWSURL', 'Related Links');
define('_MD_TCW_NEWSCOUNTER', 'Popular');
define('_MD_TCW_NEWS_ADD', 'Add news release');
define('_MD_TCW_NEWS_TO_CAL', 'Fill in the date in this message, it can be added to the calendar');
define('_MD_TCW_NEWS_TEACHER', 'Teacher');
define('_MD_TCW_NEWS_FILES', 'Related Accessories');
define('_MD_TCW_NEWS_TODAY', 'Today');
define('_MD_TCW_NEWS_PREV_MONTH', 'Previous Month');
define('_MD_TCW_NEWS_NEXT_MONTH', 'Next Month');
define("_MD_TCW_NEWS_BLOCK_LIST", "News");
define("_MD_TCW_NEWS_BLOCK_LIMIT", "Displays the number of news");
define("_MD_TCW_NEWS_BLOCK_SHOW_MODE", "Display mode");
define("_MD_TCW_NEWS_BLOCK_SHOW_MODE1", "The latest one is complete, the rest of the news presented in a strip column");
define("_MD_TCW_NEWS_BLOCK_SHOW_MODE2", "All complete presentation");
define("_MD_TCW_NEWS_BLOCK_SHOW_MODE3", "All presented in a strip column");
