<?php
define('_MD_TCW_DISCUSS', 'ChatBox');
define('_MD_TCW_DISCUSS_SHORT', 'Message');
define('_MD_TCW_DISCUSSID', 'Number');
define('_MD_TCW_REDISCUSSID', 'Reply ID');
define('_MD_TCW_DISCUSS_UID', 'Author');
define('_MD_TCW_DISCUSSTITLE', 'Topic');
define('_MD_TCW_DISCUSSCONTENT', 'Discussion');
define('_MD_TCW_DISCUSSDATE', 'Name');
define('_MD_TCW_LASTTIME', 'Last updated');
define('_MD_TCW_DISCUSSCOUNTER', 'Popular');
define('_MD_TCW_LOGIN_TO_POST', 'You must first to login to post');
define('_MD_TCW_DISCUSS_SUBMIT', 'Submit Topic');
define('_MD_TCW_DISCUSS_TO_REPLY', 'I want to reply');
define('_MD_TCW_DISCUSS_REPLY', 'Reply');
define('_MD_TCW_DISCUSS_ADD', 'Message');
define("_MD_TCW_DISCUSS_FILES", "Attachment");
define('_MD_TCW_MEM_UNAME', 'Student Account');
define('_MD_TCW_MEM_PASSWD', 'Student Password');
define("_MD_TCW_PLEASE_INPUT", "Enter ");
define("_MD_TCW_DISCUSS_BLOCK_LIST", "ChatBox");
define("_MD_TCW_DISCUSS_BLOCK_LIMIT", "Displays the number of Message");
