<?php
define('_MD_TCW_SCHEDULE', 'Class Schedule');
define('_MD_TCW_SCHEDULE_ADD', 'Add Schedule');
define('_MD_TCW_SCHEDULE_SHORT', 'Schedule');
define('_MD_TCW_SCHEDULEID', 'Schedule ID');
define('_MD_TCW_SCHEDULENAME', 'Schedule Title');
define('_MD_TCW_SCHEDULEDESC', 'Schedule Description');
define('_MD_TCW_SCHEDULEDATE', 'Date');
define('_MD_TCW_SCHEDULEUID', 'Author');
define('_MD_TCW_SCHEDULECOUNT', 'Counter');
define('_MD_TCW_SCHEDULE_BLANK', 'Empty');
define('_MD_TCW_SCHEDULE_CATE_DEMO', '');
define('_MD_TCW_SCHEDULE_SETUP_SUBJECT', 'Setup subject');
define('_MD_TCW_SCHEDULE_SET_DEFAULT', 'Default Schedule?');
define('_MD_TCW_SCHEDULE_SET_DEFAULT_DESC', 'Each site can have a "Default Schedule", which means this schedule are currently mainly used to display on the home page.');
define('_MD_TCW_SCHEDULE_MAIN_TEACHER', 'Main class teacher');
define('_MD_TCW_SCHEDULE_DEMO', 'Demo');
define('_MD_TCW_SCHEDULE_SUBJECT_TITLE', 'Subject');
define('_MD_TCW_SCHEDULE_TEACHER_NAME', 'Teacher or Class Room');
define('_MD_TCW_SCHEDULE_COLOR', 'Font Color');
define('_MD_TCW_SCHEDULE_BGCOLOR', 'Background Color');
define('_MD_TCW_SCHEDULE_ADD_ITEM', 'Add a new item');
define('_MD_TCW_SCHEDULE_PDF', 'Download Schedule');
define('_MD_TCW_SCHEDULE_BLOCK_LIST', 'Class Schedule');
define('_MD_TCW_SCHEDULE_OTHER_LIST', 'Other Schedule');
