<?php
define("_MD_TCW_SCHEDULE", "功課表");
define("_MD_TCW_SCHEDULE_ADD", "新增課表");
define("_MD_TCW_SCHEDULE_SHORT", "課表");
define("_MD_TCW_SCHEDULEID", "課表編號");
define("_MD_TCW_SCHEDULENAME", "課表名稱");
define("_MD_TCW_SCHEDULEDESC", "課表說明");
define("_MD_TCW_SCHEDULEDATE", "發布日期");
define("_MD_TCW_SCHEDULEUID", "發布者");
define("_MD_TCW_SCHEDULECOUNT", "人氣");
define("_MD_TCW_SCHEDULE_BLANK", "空堂");
define("_MD_TCW_SCHEDULE_CATE_DEMO", "可建立分類如：「%s 學年度第 %s 學期」");
define("_MD_TCW_SCHEDULE_SETUP_SUBJECT", "科目設定");
define("_MD_TCW_SCHEDULE_SET_DEFAULT", "是否以此課表為「預設顯示課表」？");
define("_MD_TCW_SCHEDULE_SET_DEFAULT_DESC", "每個網站只能有一個「預設顯示課表」，意味者目前以此課表為主，用來顯示於首頁。");
define("_MD_TCW_SCHEDULE_MAIN_TEACHER", "級任老師");
define("_MD_TCW_SCHEDULE_DEMO", "範例");
define("_MD_TCW_SCHEDULE_SUBJECT_TITLE", "科目名稱");
define("_MD_TCW_SCHEDULE_TEACHER_NAME", "教師姓名或教室");
define("_MD_TCW_SCHEDULE_COLOR", "文字顏色");
define("_MD_TCW_SCHEDULE_BGCOLOR", "背景顏色");
define("_MD_TCW_SCHEDULE_ADD_ITEM", "新增一個項目");
define("_MD_TCW_SCHEDULE_PDF", "下載課表");
define("_MD_TCW_SCHEDULE_BLOCK_LIST", "功課表");
define("_MD_TCW_SCHEDULE_OTHER_LIST", "其他課表查詢");
