<?php
define("_MD_TCW_WORKS", "Works Gallery");
define("_MD_TCW_WORKS_ADD", "Upload works");
define("_MD_TCW_WORKS_SHORT", "Works");
define("_MD_TCW_WORKS_ID", "Works ID");
define("_MD_TCW_WORKS_DESC", "Works Description");
define("_MD_TCW_WORKS_DATE", "Works updated");
define("_MD_TCW_WORKS_NAME", "Works Title");
define("_MD_TCW_WORKS_UPLOAD", "Upload works");
define("_MD_TCW_WORKS_COUNT", "Counter");
define("_MD_TCW_WORK_BLOCK_LIST", "List Works");
define("_MD_TCW_WORK_BLOCK_RANDOM", "Random Works");
define("_MD_TCW_WORK_BLOCK_LATEST", "Latest Works");
define("_MD_TCW_WORK_BLOCK_LIMIT", "Displays the number of works");
define('_MD_TCW_WORKS_KIND', 'Upload method');
define('_MD_TCW_WORKS_KIND_DEFAULT', 'Upload by administrators, and immediate displayed');
define('_MD_TCW_WORKS_KIND_MEM_NOW', 'Uploaded by students, and immediate displayed');
define('_MD_TCW_WORKS_KIND_MEM_AFTER_END', 'Uploaded by students, and displayed after the deadline');
define('_MD_TCW_WORKS_END_DATE', 'Deadline');
define('_MD_TCW_WORKS_ENABLE', 'Enable?');
define("_MD_TCW_WORKS_DESCRIPTION", "Description");
define("_MD_TCW_WORKS_AUTHOR", "Author");
define("_MD_TCW_WORKS_DISPLAY_DATE", "Display after %s");
define("_MD_TCW_WORKS_UPLOADED_WORKS", "Uploaded Files");
define("_MD_TCW_WORKS_WORKS_SCORE_FORM", "Works Comments");
define("_MD_TCW_WORKS_WORKS_SCORE", "Works Score");
define("_MD_TCW_WORKS_WORKS_JUDGMENT", "Works Comments");
