<?php
define("_MD_TCW_WORKS", "作品分享");
define("_MD_TCW_WORKS_ADD", "上傳作品");
define("_MD_TCW_WORKS_SHORT", "作品");
define("_MD_TCW_WORKS_ID", "作品編號");
define("_MD_TCW_WORKS_DESC", "主題說明");
define("_MD_TCW_WORKS_DATE", "上傳日期");
define("_MD_TCW_WORKS_NAME", "作品主題");
define("_MD_TCW_WORKS_UPLOAD", "上傳作品");
define("_MD_TCW_WORKS_COUNT", "人氣");
define("_MD_TCW_WORK_BLOCK_LIST", "作品分享列表");
define("_MD_TCW_WORK_BLOCK_RANDOM", "隨機作品分享");
define("_MD_TCW_WORK_BLOCK_LATEST", "最新作品分享");
define("_MD_TCW_WORK_BLOCK_LIMIT", "顯示作品數量");
define('_MD_TCW_WORKS_KIND', '上傳方式');
define('_MD_TCW_WORKS_KIND_DEFAULT', '由管理員上傳，並即時公開');
define('_MD_TCW_WORKS_KIND_MEM_NOW', '由學生上傳，並即時公開');
define('_MD_TCW_WORKS_KIND_MEM_AFTER_END', '由學生上傳，並於截止日後公開');
define('_MD_TCW_WORKS_END_DATE', '上傳截止日期');
define('_MD_TCW_WORKS_ENABLE', '是否啟用？');
define("_MD_TCW_WORKS_DESCRIPTION", "作品描述");
define("_MD_TCW_WORKS_AUTHOR", "上傳者");
define("_MD_TCW_WORKS_DISPLAY_DATE", "預計 %s 開放");
define("_MD_TCW_WORKS_UPLOADED_WORKS", "已上傳檔案");
define("_MD_TCW_WORKS_WORKS_SCORE", "作品評分");
