<?php
define("_MD_TCW_SYSTEM", "System");
define("_MD_TCW_SYSTEM_SHORT", "System");
define("_MD_TCW_SYSTEM_BLOCK_MY_MENU", "My Menu");
define("_MD_TCW_SYSTEM_BLOCK_LOGIN", "Login");
define("_MD_TCW_SYSTEM_BLOCK_SEARCH", "Search");
define("_MD_TCW_SYSTEM_BLOCK_QRCODE", "QR Code");
define("_MD_TCW_SYSTEM_BLOCK_WEBLIST", "Web List");
define("_MD_TCW_SYSTEM_BLOCK_RRSSB", "Social Sharing Buttons");
define("_MD_TCW_SYSTEM_BLOCK_MOEDICT", "Search MOEDict");
define("_MD_TCW_SYSTEM_BLOCK_DREYE", "Dr.eye dictionary");
define("_MD_TCW_SYSTEM_BLOCK_WIKI", "Search Wikipedia");

define('_MD_TCW_TO_MY_WEB', 'back to my "%s"');
define('_MD_TCW_WEB_CONFIG', 'Web Config');
define("_MD_TCW_WEB_BLOCK_CONFIG", "Block Config");
define("_MD_TCW_ENABLE_PLUGIN", "Enable");
define("_MD_TCW_ENABLE", "Enable");
define("_MD_TCW_SEARCH", "Search");
define("_MD_TCW_LOGIN", "Login");
define("_MD_TCW_ID", "ID");
define("_MD_TCW_PASSWD", "Password");
define("_MD_TCW_MEM_UNAME", "Student ID");
define("_MD_TCW_MEM_PASSWD", "Student Password");
define("_MD_TCW_IM_MEM", "I am Student");
define("_MD_TCW_SEARCH_MOEDICT", "Search");
define("_MD_TCW_SEARCH_MOEDICT_KEYWORD", "Key Word");
define("_MD_TCW_SEARCH_DREYEDICT", "Search");
define("_MD_TCW_SEARCH_DREYEDICT_KEYWORD", "Key Word");
define("_MD_TCW_OPENID_LOGIN", "%s OpenID");
define("_MD_TCW_LOGIN_BY_OPENID", "OpenID Login");
define("_MD_TCW_LOGIN_BY_MEM", " Login");
define("_MD_TCW_LOGIN_BY_XOOPS", "XOOPS Login");
define("_MD_TCW_SEARCH_WIKI", "Search");
define("_MD_TCW_SEARCH_WIKI_KEYWORD", "Key Word");
define("_MD_TCW_NEWS_BLOCK_LOGIN_METHOD", "Choose Login mode");
define("_MD_TCW_SYSTEM_BLOCK_PM25", "Pm2.5 Forecast");
define("_MD_TCW_SYSTEM_BLOCK_PSI", "PSI Forecast");
define("_MD_TCW_SYSTEM_BLOCK_TALKIO", "tlk.io chat");
define("_MD_TCW_SYSTEM_BLOCK_TLKIO_NAME", "Channel name");
define("_MD_TCW_SYSTEM_BLOCK_TLKIO_THEME", "Theme");
define("_MD_TCW_SYSTEM_BLOCK_TLKIO_THEME_DAY", "Day");
define("_MD_TCW_SYSTEM_BLOCK_TLKIO_THEME_NIGHT", "Night");
define("_MD_TCW_SYSTEM_BLOCK_TLKIO_THEME_POP", "Pop");
define("_MD_TCW_SYSTEM_BLOCK_TLKIO_THEME_MINIMAL", "Minmal");
define("_MD_TCW_SYSTEM_BLOCK_TLKIO_HEIGHT", "Height");

define('_MD_TCW_SYSTEM_BLOCK_COUNTDOWN', 'Count Down');
define('_MD_TCW_SYSTEM_BLOCK_COUNTDOWN_TITLE_DEF', date("Y") . ' Christmas');
define('_MD_TCW_SYSTEM_BLOCK_COUNTDOWN_TITLE', 'Event Title');
define('_MD_TCW_SYSTEM_BLOCK_COUNTDOWN_DATE', 'Event DateTime');
define('_MD_TCW_SYSTEM_BLOCK_FLICKRIT', 'Flickrit');
define('_MD_TCW_SYSTEM_BLOCK_FLICKRIT_TYPE', 'SLIDESHOW SELECTION');
define('_MD_TCW_SYSTEM_BLOCK_FLICKRIT_TYPE_FLICKR', 'Flickr');
define('_MD_TCW_SYSTEM_BLOCK_FLICKRIT_TYPE_PICASA', 'Picasa');
define('_MD_TCW_SYSTEM_BLOCK_FLICKRIT_SETID', 'Album ID or User ID');

define('_MD_TCW_SYSTEM_BLOCK_FLICKRIT_KIND', 'SELECTION');
define('_MD_TCW_SYSTEM_BLOCK_FLICKRIT_KIND_SETID', 'Album ID');
define('_MD_TCW_SYSTEM_BLOCK_FLICKRIT_KIND_USERID', 'User ID');
