<?php
define("_MD_TCW_SYSTEM", "班網系統");
define("_MD_TCW_SYSTEM_SHORT", "系統");
define("_MD_TCW_SYSTEM_BLOCK_MY_MENU", "我的選單");
define("_MD_TCW_SYSTEM_BLOCK_LOGIN", "登入");
define("_MD_TCW_SYSTEM_BLOCK_SEARCH", "搜尋");
define("_MD_TCW_SYSTEM_BLOCK_QRCODE", "QRCode");
define("_MD_TCW_SYSTEM_BLOCK_WEBLIST", "網站列表");
define("_MD_TCW_SYSTEM_BLOCK_RRSSB", "推文工具");
define("_MD_TCW_SYSTEM_BLOCK_MOEDICT", "萌典查生字");
define("_MD_TCW_SYSTEM_BLOCK_DREYE", "Dr.eye 英漢字典");
define("_MD_TCW_SYSTEM_BLOCK_WIKI", "維基百科查詢");

define("_MD_TCW_TO_MY_WEB", "連回「%s」");
define("_MD_TCW_WEB_CONFIG", "網站設定");
define("_MD_TCW_WEB_BLOCK_CONFIG", "區塊設定");
define("_MD_TCW_ENABLE_PLUGIN", "啟用此功能");
define("_MD_TCW_ENABLE", "啟用");
define("_MD_TCW_SEARCH", "搜尋");
define("_MD_TCW_ID", "帳號");
define("_MD_TCW_PASSWD", "密碼");
define("_MD_TCW_MEM_UNAME", "學生帳號");
define("_MD_TCW_MEM_PASSWD", "學生密碼");
define("_MD_TCW_SEARCH_MOEDICT", "查生字");
define("_MD_TCW_SEARCH_MOEDICT_KEYWORD", "請輸入生字或生詞");
define("_MD_TCW_SEARCH_DREYEDICT", "查單字");
define("_MD_TCW_SEARCH_DREYEDICT_KEYWORD", "請輸入英文單字或中文");
define("_MD_TCW_OPENID_LOGIN", "%s登入");
define("_MD_TCW_LOGIN_BY_OPENID", "網站擁有者 OpenID 登入");
define("_MD_TCW_LOGIN_BY_MEM", "帳號登入");
define("_MD_TCW_LOGIN_BY_XOOPS", "一般XOOPS登入");
define("_MD_TCW_LOGIN_BY_PARENTS", "家長登入");
define("_MD_TCW_REGIST_BY_PARENTS", "申請家長帳號");
define("_MD_TCW_FORGET_PARENTS_PASSWD", "忘記密碼");

define("_MD_TCW_SEARCH_WIKI", "查百科");
define("_MD_TCW_SEARCH_WIKI_KEYWORD", "請輸入關鍵字");
define("_MD_TCW_NEWS_BLOCK_LOGIN_METHOD", "選擇欲開放的登入方式");
define("_MD_TCW_SYSTEM_BLOCK_PM25", "懸浮微粒 (pm2.5) 預報");
define("_MD_TCW_SYSTEM_BLOCK_PSI", "空氣品質 (PSI) 預報");
define("_MD_TCW_SYSTEM_BLOCK_TALKIO", "線上聊天室");
define("_MD_TCW_SYSTEM_BLOCK_TLKIO_NAME", "聊天室名稱（限英文、數字、底線）");
define("_MD_TCW_SYSTEM_BLOCK_TLKIO_THEME", "聊天室佈景");
define("_MD_TCW_SYSTEM_BLOCK_TLKIO_THEME_DAY", "淡藍");
define("_MD_TCW_SYSTEM_BLOCK_TLKIO_THEME_NIGHT", "深灰");
define("_MD_TCW_SYSTEM_BLOCK_TLKIO_THEME_POP", "粉紅");
define("_MD_TCW_SYSTEM_BLOCK_TLKIO_THEME_MINIMAL", "淺灰");
define("_MD_TCW_SYSTEM_BLOCK_TLKIO_HEIGHT", "聊天室高度");

define('_MD_TCW_SYSTEM_BLOCK_COUNTDOWN', '倒數計時');
define('_MD_TCW_SYSTEM_BLOCK_COUNTDOWN_TITLE_DEF', date("Y") . ' 聖誕節');
define('_MD_TCW_SYSTEM_BLOCK_COUNTDOWN_TITLE', '事件標題');
define('_MD_TCW_SYSTEM_BLOCK_COUNTDOWN_DATE', '事件日期時間');
define('_MD_TCW_SYSTEM_BLOCK_FLICKRIT', '外部相簿崁入');
define('_MD_TCW_SYSTEM_BLOCK_FLICKRIT_TYPE', '相簿來源');
define('_MD_TCW_SYSTEM_BLOCK_FLICKRIT_TYPE_FLICKR', 'Flickr');
define('_MD_TCW_SYSTEM_BLOCK_FLICKRIT_TYPE_PICASA', 'Picasa');
define('_MD_TCW_SYSTEM_BLOCK_FLICKRIT_SETID', '相簿編號或使用者帳號');

define('_MD_TCW_SYSTEM_BLOCK_FLICKRIT_KIND', '套用方式');
define('_MD_TCW_SYSTEM_BLOCK_FLICKRIT_KIND_SETID', '相簿編號（指定相簿）');
define('_MD_TCW_SYSTEM_BLOCK_FLICKRIT_KIND_USERID', '使用者帳號（最新照片）');
define('_MD_TCW_SYSTEM_BLOCK_TAGS', '標籤');
define('_MD_TCW_SYSTEM_BLOCK_TAGS_MODE', '標籤顯示模式');
define('_MD_TCW_SYSTEM_BLOCK_TAGS_MODE_LIST', '標籤列表');
define('_MD_TCW_SYSTEM_BLOCK_TAGS_MODE_CLOUD', '標籤雲');
define('_MD_TCW_SYSTEM_BLOCK_MIN_HEIGHT', '標籤雲高度');
