<?php
define('_MD_TCW_ACTION', '活動剪影');
define('_MD_TCW_ACTION_ADD', '上傳圖檔');
define('_MD_TCW_ACTION_SHORT', '活動');
define('_MD_TCW_ACTIONID', '活動編號');
define('_MD_TCW_ACTIONNAME', '活動名稱');
define('_MD_TCW_ACTIONDESC', '活動說明');
define('_MD_TCW_ACTIONDATE', '活動日期');
define('_MD_TCW_ACTIONPLACE', '活動地點');
define('_MD_TCW_ACTIONUID', '發布者');
define('_MD_TCW_ACTIONCOUNT', '人氣');
define('_MD_TCW_ACTION_UPLOAD', '上傳圖檔');
define('_MD_TCW_ACTION_BLOCK_LIST', '活動剪影');
define('_MD_TCW_ACTION_BLOCK_LIMIT', '顯示活動數量');
define('_MD_TCW_ACTION_BLOCK_SLIDE', '活動剪影秀');
define('_MD_TCW_AUTO_PLAY_IMAGES', '圖片自動播放設定（毫秒）');
define('_MD_TCW_AUTO_PLAY_IMAGES_DESC', '如：設「3000」為3秒，設0則不自動播放');
define('_MD_TCW_ACTION_GPHOTO', 'Google 相簿（建議）');
define('_MD_TCW_ACTION_UPLOAD_METHOD', '加入相片方式');
define('_MD_TCW_ACTION_GPHOTO_URL', 'Google 共享相簿網址');
define('_MD_TCW_ACTION_GPHOTO_URL_DEMO', 'https://photos.google.com/share/相簿ID?key=相簿金鑰');
define('_MD_TCW_ACTION_GPHOTO_URL_HEPL', '<ol><li>請先連到<a href="https://photos.google.com/albums" target="_blank">Google 相簿</a></li><li>若裡面沒有任何相簿，請直接按上方「+建立」，選擇「共享相簿」建立之即可。</li><li>若是已有相簿，但非「共享相簿」，那就請先進入該相簿，點擊右上角圖示：<br><img src="plugins/action/images/setup0.png" class="img-fluid img-responsive" style="margin-bottom:10px;"></li><li>點擊「選項」，然後開啟分享：<br><img src="plugins/action/images/setup.png" class="img-fluid img-responsive" style="margin-bottom:10px;"></li><li>此時，網址格式應為 <strong style="background: #fcffe5;padding:4px 8px;border:1px solid gray;">https://photos.google.com/<span style="color:red;">share</span>/相簿ID<span style="color:red;">?key=</span>相簿金鑰</strong> 才正確（即網址列上的網址，不是縮短後的分享網址）</li><li>每次擷取最多 500 張照片，故相簿中照片若超過500張建議分成第二本相簿。</li></ol>');

define('_MD_TCW_ACTION_BLOCK_SLIDE_RAND', '隨機顯示');
define('_MD_TCW_ACTION_BLOCK_SLIDE_LATEST', '顯示最新活動');
define('_MD_TCW_ACTION_BLOCK_ALBUM', '欲顯示活動');
define('_MD_TCW_ACTION_BLOCK_PHOTOS', '活動相片');
define('_MD_TCW_ACTION_VIEW_ORIGINAL_IMAGE', '觀看原圖');
define('_MD_TCW_ACTION_BLOCK_PHOTOS_PLACEHOLDER', '設為 0 就是全部');
define('_MD_TCW_ACTION_BLOCK_ORDER', '相片排序方式');
define('_MD_TCW_ACTION_BLOCK_ORDER_RAND', '隨機排序');
define('_MD_TCW_ACTION_BLOCK_ORDER_DEFAULT', '依據既有排序');
